version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
